### ISSUE TITLE
Out of date hashtable.bin will cause problems with Patch command...

### ISSUE THREAD

**Issue by ApacheThunder** [VelouriasMoon/TotkRSTB#4]
Trying to port a WIP mod I was working on to 1.2. So I gave this tool a whirl and it 99% works...Until game update version specific files are involved. One example:

RSDB/AttachmentActorInfo.Product.120.rstbl.byml

This entry along with it's 1.1.2 equivalent are not updated in the output RSTDB file...I have to assume this is because of the use of a hastable.bin file?

Why is this file needed? I understand a bit how the RSTDB file works. It's just a collection of hashes with sizes I assume so there's no strings saved there so you have to save the known ones somewhere.

But this should only be required if trying to dump a RSTDB file to yaml text. For the patch command it should instead load hashes from the vanilla rstdb file provided in the command line arguments as a base for if it needs to update or add a new hash.

At least to my understanding this is what is happening with NX-Editor's RSTDB editor. That editor has no issues finding a hash if you know the exact string which is how I've been updating that file up till I gave this tool a try since I needed a quicker way to port my mod to a newer version of the mod.

I would recommend following a similar approach when using the patch feature. The hash bin file should only be needed for things that really need it like the rstb to yaml converter where the string information wouldn't otherwise be known.

For patching, strings don't have to be known. Just generate the hashes from all the strings in the input YAML file and look for them in the vanilla RSTDB and if it's not there that means the yaml's string is a new one and it should be added. Instead what I think is what is happening is this tool is instead looking at the hashtable file instead for this and is possibly attempting to add my 1.1.2/1.2.0 related strings to the RSTDB despite them already existing in the vanilla file.

This can have unpredictable behavior. For future proofing I would recommend the suggested approach so that future game updates don't break things.

EDIT:

Ok I took a look at how the MakeRSTBPatch function is running. It creates a new instance of HashTable so I took a look at it's class initializer. When a new instance is created it appears to use a Strings dictionary which gets built by reading the hashtable.bin file so the string lookup function in MakeRSTBPatch does appear to be using that.

I would think it's a better idea to rebase MakeRSTBPatch to not use that since it doesn't need to know the strings as those are provided by the yaml input file. It needs to load the existing hashes into a dictionary/list/array from the provided vanilla RSTB file and then generate a hash for each string provided in the YAML file. For ones that aren't in the dictionary it adds it as a new hash but for the existing ones it finds it will do the usuall update if number is larger routine.

EDIT2:

It doesn't appear to add new entries for strings it doesn't find. If it doesn't find a entry for a string in YAML it appears to skip it. (where as the correct action would be to add it as a new hash in the RSTB)

I added a new icon graphic in UI/Tex folder and thus it needs an entry in RSTB. So I would recommend resolving this too. ;)

I shudder to think how many mods this tool has silently broken. :(

**Comment by DarkGuardAtHome** [comment]
Nice attitude, dude

**Comment by MediaMoots** [comment]
@ApacheThunder Did you find a solution?

**Comment by MediaMoots** [comment]
@ApacheThunder 
You can try PR #7 
It should fix all the issues you mentioned.
